### PR TITLE
Proposal to restructure Drupal module

### PR DESCRIPTION
**Pull request by dakala**
This is a first attempt at restructuring the module and make it conform to Drupal best practice with the aim of contributing it back to the Drupal community. Thanks.

### CODE REVIEW

**Comment by dakala** [comment]
Issue: https://github.com/Shorthand/shorthand_connect_drupal/issues/2

**Comment by simultech** [comment]
Hi Dakala,

Thank you so much for your PR - looks wonderful.  Is there anything you would like me to look at specifically or you are happy for the merge (it looks much improved).  Happy to merge if you are happy with it.

Also I would like to add you to an authors file if you don't mind?  Just so you are credited.  But I understand if you do not wish to / are unable to.

**Comment by dakala** [comment]
@simultech Quite happy for it to be merged. It's a clean up and making sure it works. An authors file would be great too.

Let's discuss other issues I've created on moving the development forward. Thanks.

**Comment by simultech** [comment]
Sounds great, merged.

**Comment by simultech** [comment]
@dakala I've added an AUTHORS file, could you do a PR and include yourself?

**Pull request merged**
