### PR TITLE
Feature/v2 support

### PR DESCRIPTION
**Pull request by simultech**

### CODE REVIEW

**Comment by simultech** [comment]
@dakala looking at merging this, you are more than welcome to review before-hand if you like?  It shouldn't affect v1 functionality, but just in case there are things that you spot from your expertise.  I'll probably look at merging this at the start of next week.

**Comment by dakala** [comment]
@simultech Please go ahead and merge if you're happy since it won't affect v1 functionality anyway. We should probably open a Drupal 7.x-2.x branch for this but we can do that later. 

I don't know if you've noticed but work has already started on a Drupal 8 version of SH module - https://github.com/dakala/shorthand_connect_drupal/tree/8.x-1.x

**Comment by simultech** [comment]
@dakala hey there, just wondering if you are still active on working on your 8x shorthand plugin.  If so, are you focusing on v1 or v2 support?  I'm looking at doing a v2 d8 version for some other users, but didn't want to step into it if you are working on something similar already.  

Also I think the tree idea is good, one issue we are running into is older clients who were using the module before it got renamed, they are having issues upgrading.  So I was thinking the easiest thing to do would be to keep a branch for them that uses the old shorthand_connect name.  Any thoughts?

**Comment by dakala** [comment]
@simultech Hi! Sorry, haven't had time to work on SH for some time now since I changed jobs. However, there's already some work on 8.x-1.x branch - https://github.com/dakala/shorthand_connect_drupal/pull/1 

And yes, we need 7.x-2.x and 8.x-2.x branches to support the v2 API. 

The best solution for those using the old version of the module would be to convert their nodes to the new module. An option would be to do the move for them in an update hook in the new module but it's a question of making out time for implementing this solution.

Continuing a branch with the old `shorthand_connect` name is something I wouldn't be keen on even though it's the easiest way out. We might end up with a lot of branches to keep in sync etc.

**Comment by simultech** [comment]
@dakala not a problem at all!  Congrats on new job - are you still working with SH?  If so awesome!  But if not no pressure at all if you are busy.  

I've just changed naming conventions for branches now, and just started working on 8.x-2.x.  

Good point about the branching with `shorthand_connect`.

**Pull request closed without merging**
